Customize footer
concello-santiago-de-compostela/consul pull request #20
Opened 2020-12-07 16:04 UTC by javierm

## References

* Closes #6

## Objectives

* Make the footer look like the ones in other similar pages

## Visual Changes

![The footer shows contact information and links to transparency and open data](https://user-images.githubusercontent.com/35156/98565866-67705100-22ae-11eb-982b-fa1814f66ab4.png)

2020-12-09 14:53 UTC, Senen requested changes
Hi Javi, I left some comments, all of them regarding translations.

Also noticed that with screen sizes between 640px to 1170px (medium and large Foundation media queries breakpoints) the footer is not rendered properly. 

Here is a patch where I tried to add Foundation column styles to the respective layers so we keep the spacing correct for all screen sizes.

[FooterSpacing.txt](https://github.com/concello-santiago-de-compostela/consul/files/5666754/FooterSpacing.txt)

This another patch is the same but changes the distribution as the following screenshot shows:
[FooterSpacingAndDistribution.txt](https://github.com/concello-santiago-de-compostela/consul/files/5666755/FooterSpacingAndDistribution.txt)

<img width="945" alt="Captura de pantalla 2020-12-09 a las 16 03 49" src="https://user-images.githubusercontent.com/15726/101647118-a7a32a80-3a38-11eb-9578-bc330fe0aa39.png">

2020-12-09 14:53 UTC, Senen commented on config/locales/custom/es/general.yml
> +  contact:
I think we are missing the Galician translation for these strings:

```
    phone_1: "%{phone} (Centro de Atención Telefónica)"
    phone_2: "%{phone} (Concello)"
```

2020-12-09 14:53 UTC, Senen commented on config/locales/custom/es/general.yml
> +      description: "Obtén cualquier información sobre el Concello de Santiago"
I think we are missing the Galician translation for this string:
`"Obter información sobre o Concello de Santiago"`

2020-12-09 14:53 UTC, Senen commented on config/locales/custom/es/general.yml
> +      description: "Todos los datos del Ayuntamiento son tuyos."
Same here:
`"Todos os datos do Concello son teus."`

2020-12-09 14:53 UTC, Senen commented on config/locales/custom/es/general.yml
> +      open_source: software libre
As the Galician translation is the same "software libre" we can avoid to add the translation into the `gl` files.

2020-12-09 14:53 UTC, Senen commented on config/locales/es/settings.yml
> +    contact:
I think we should not modify the original Spanish file for settings translations, we could move them to the custom file too `config/locales/custom/es/settings.yml`.

2020-12-09 15:19 UTC, javierm commented on config/locales/custom/es/general.yml
> +  contact:
Right. We'll ask for translations :+1:.

2020-12-09 16:02 UTC, javierm commented on config/locales/es/settings.yml
> +    contact:
You're absolutely right :smile:. Fixed, thanks!

2020-12-10 13:02 UTC, Senen approved these changes

2020-12-10 13:04 UTC, Senen approved these changes

2020-12-10 13:37 UTC, merged